# Generated by Django 5.0.4 on 2024-05-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
